<font size="3">Goals:</font>

-Transform 1 and 2-dimensional data in Python Lists and Dictionaries into Numpy Arrays

-Apply reshape, join, and split operations to Numpy arrays

-Apply aggregate functions like mean, average, product, median, standard deviation, variance to Numpy arrays


by leveraging the real world data of the NBA Lakers starting players to calculate their BMIs (Body Mass Index).

In [143]:
import numpy as np
import json
import pandas as pd

In [144]:
with open('./data.json', 'r', encoding='utf-8') as f:
    bmi_data = json.loads(f.read())

with open('./efficiency_data.json', 'r', encoding='utf-8') as f:
    stats_data = json.loads(f.read())

In [145]:
bmi_data

{'Lakers': [{'Name': 'Patrick Beverly', 'Height': 73, 'Weight': 180},
  {'Name': 'Lonnie Walker', 'Height': 76, 'Weight': 204},
  {'Name': 'Troy Brown', 'Height': 78, 'Weight': 215},
  {'Name': 'Lebron James', 'Height': 81, 'Weight': 250},
  {'Name': 'Anthony Davis', 'Height': 82, 'Weight': 253}],
 'Golden State Warriors': [{'Name': 'Stephen Curry',
   'Height': 74,
   'Weight': 185},
  {'Name': 'Klay Thompson', 'Height': 78, 'Weight': 220},
  {'Name': 'Andrew Wiggins', 'Height': 79, 'Weight': 197},
  {'Name': 'Draymond Green', 'Height': 78, 'Weight': 230},
  {'Name': 'Kevon Looney', 'Height': 81, 'Weight': 222}],
 'Top 10 Highest Paid NBA Players': [{'Name': 'Lebron James',
   'Height': 81,
   'Weight': 250},
  {'Name': 'Russell Westbrook', 'Height': 75, 'Weight': 200},
  {'Name': 'Kevin Durant', 'Height': 82, 'Weight': 240},
  {'Name': 'James Harden', 'Height': 77, 'Weight': 220},
  {'Name': 'Stephen Curry', 'Height': 74, 'Weight': 185},
  {'Name': 'Damian Lillard', 'Height': 74, 'We

In [146]:
stats_data

{'Lakers': [{'Name': 'Patrick Beverly',
   'PTS': 533,
   'REB': 240,
   'AST': 268,
   'STL': 67,
   'BLK': 52,
   'FGM': 259,
   'FTM': 37,
   'TO': 73},
  {'Name': 'Lonnie Walker',
   'PTS': 849,
   'REB': 181,
   'AST': 152,
   'STL': 44,
   'BLK': 19,
   'FGM': 453,
   'FTM': 32,
   'TO': 71},
  {'Name': 'Troy Brown',
   'PTS': 283,
   'REB': 203,
   'AST': 66,
   'STL': 36,
   'BLK': 5,
   'FGM': 150,
   'FTM': 6,
   'TO': 26},
  {'Name': 'Lebron James',
   'PTS': 1695,
   'REB': 459,
   'AST': 349,
   'STL': 73,
   'BLK': 59,
   'FGM': 581,
   'FTM': 82,
   'TO': 196},
  {'Name': 'Anthony Davis',
   'PTS': 927,
   'REB': 394,
   'AST': 122,
   'STL': 49,
   'BLK': 90,
   'FGM': 325,
   'FTM': 70,
   'TO': 82}],
 'Golden State Warriors': [{'Name': 'Stephen Curry',
   'PTS': 1630,
   'REB': 335,
   'AST': 404,
   'STL': 85,
   'BLK': 23,
   'FGM': 689,
   'FTM': 23,
   'TO': 206},
  {'Name': 'Klay Thompson',
   'PTS': 652,
   'REB': 125,
   'AST': 88,
   'STL': 16,
   'BLK': 17,
 

In [147]:
for data in bmi_data["Lakers"]:
    print(data)

{'Name': 'Patrick Beverly', 'Height': 73, 'Weight': 180}
{'Name': 'Lonnie Walker', 'Height': 76, 'Weight': 204}
{'Name': 'Troy Brown', 'Height': 78, 'Weight': 215}
{'Name': 'Lebron James', 'Height': 81, 'Weight': 250}
{'Name': 'Anthony Davis', 'Height': 82, 'Weight': 253}


In [148]:
for key,value in data.items():
    print(key,value)

Name Anthony Davis
Height 82
Weight 253


In [149]:
lakers_height = [value for data in bmi_data["Lakers"] for key, value in data.items() if key =="Height"]
print(lakers_height)

[73, 76, 78, 81, 82]


In [150]:
lakers_weight = [value for data in bmi_data["Lakers"] for key, value in data.items() if key == "Weight"]
print(lakers_weight)

[180, 204, 215, 250, 253]


In [151]:
pts = [value for data in stats_data["Lakers"] for key, value in data.items() if key == "PTS"]
pts

[533, 849, 283, 1695, 927]

In [152]:
reb = [value for data in stats_data["Lakers"] for key, value in data.items() if key == "REB"]
reb

[240, 181, 203, 459, 394]

In [153]:
ast = [value for data in stats_data["Lakers"] for key, value in data.items() if key == "AST"]
ast

[268, 152, 66, 349, 122]

In [154]:
stl = [value for data in stats_data["Lakers"] for key, value in data.items() if key == "STL"]
stl

[67, 44, 36, 73, 49]

In [155]:
blk = [value for data in stats_data["Lakers"] for key, value in data.items() if key == "BLK"]
blk

[52, 19, 5, 59, 90]

In [156]:
mfg = [value for data in stats_data["Lakers"] for key, value in data.items() if key == "FGM"]
mfg

[259, 453, 150, 581, 325]

In [157]:
mft  = [value for data in stats_data["Lakers"] for key, value in data.items() if key == "FTM"]
mft

[37, 32, 6, 82, 70]

In [158]:
tov = [value for data in stats_data["Lakers"] for key, value in data.items() if key == "TO"]
tov

[73, 71, 26, 196, 82]

In [159]:
lakers_height_array = np.array(lakers_height)
lakers_weight_array = np.array(lakers_weight)
pts_array = np.array(pts)
reb_array = np.array(reb)
ast_array = np.array(ast)
stl_array = np.array(stl)
blk_array = np.array(blk)
mfg_array = np.array(mfg)
mft_array = np.array(mft)
tov_array = np.array(tov)

lakers_height_array


array([73, 76, 78, 81, 82])

In [160]:
example_2d = [[1,1,1],[1,1,1]]
print(np.array(example_2d))

[[1 1 1]
 [1 1 1]]


In [161]:
# convert the weights from pounds to kilos

lakers_weight_kg = lakers_weight_array * 0.454
lakers_weight_kg

array([ 81.72 ,  92.616,  97.61 , 113.5  , 114.862])

In [162]:
# convert the heights from inches to centimeters
lakers_height_cm = lakers_height_array * 2.54
lakers_height_cm

array([185.42, 193.04, 198.12, 205.74, 208.28])

In [163]:
# BMI Calculator

def bmi_calculator(system, weight, height):
    """
    This function calculates the BMI of NBA players using either the metric system or the imperial system
    """
    BMI = None 
    if system == "imperial":
        BMI = weight/(height**2) * 703
    elif system == "metric":
        BMI = weight/(height**2) * 10000
    return BMI

In [164]:
bmi_calculator("imperial", lakers_weight_array, lakers_height_array)

array([23.74554325, 24.82894737, 24.8430309 , 26.78707514, 26.45136823])

In [165]:
bmi_calculator("metric", lakers_weight_kg, lakers_height_cm)

array([23.769235  , 24.85372007, 24.86781765, 26.81380153, 26.47775968])

In [166]:
# Caclulating the BMI for the Golden State Warriors starting team

# storing the heights and weights for the Golden State Warriors starting team in a list respectively
gsw_height = [value for data in bmi_data["Golden State Warriors"] for key, value in data.items() if key == "Height"]
gsw_weight = [value for data in bmi_data["Golden State Warriors"] for key, value in data.items() if key == "Weight"]
gsw_weight

[185, 220, 197, 230, 222]

In [167]:
# converting the lists into a numpy array
gsw_height_array = np.array(gsw_height)
gsw_weight_array = np.array(gsw_weight)
gsw_height_array, gsw_weight_array

(array([74, 78, 79, 78, 81]), array([185, 220, 197, 230, 222]))

In [168]:
# Converting imperial data to metrics
gsw_weight_kg = gsw_weight_array * 0.454
gsw_height_cm = gsw_height_array * 2.54
gsw_height_cm, gsw_weight_kg

(array([187.96, 198.12, 200.66, 198.12, 205.74]),
 array([ 83.99 ,  99.88 ,  89.438, 104.42 , 100.788]))

In [169]:
# Calculating the BMI
print(bmi_calculator("imperial",gsw_weight_array, gsw_height_array))
print(bmi_calculator("metric",gsw_weight_kg, gsw_height_cm))

[23.75       25.42077581 22.19051434 26.57626561 23.78692273]
[23.7736962  25.44613899 22.21265458 26.60278167 23.81065576]


In [170]:
# Calculating the player efficiency rates with numpy

# EFF= (PTS + REB + AST + STL + BLK - Missed FG - Missed FT - TOV) 

lakers_players_efficiency = pts_array + reb_array + ast_array + stl_array + blk_array - mfg_array - mft_array - tov_array
lakers_players_efficiency

array([ 791,  689,  411, 1776, 1105])

Performing aggregate functions on the Lakers starting team

In [173]:
# Summation  (result in inches, pounds)
print(np.sum(lakers_height_array))
print(np.sum(lakers_weight_array))

390
1102


In [174]:
# Alternative method:
lakers_height_array.sum()

390

In [177]:
# Average weight of Lakers players (pounds)
np.average(lakers_weight_array)

220.4

In [178]:
# Average height of Lakers players (inches)
np.average(lakers_height_array)

78.0

In [181]:
# Min and Max of an array, in this case of weight - pounds
lakers_weight_array.min(), lakers_weight_array.max()

(180, 253)

In [183]:
# Min and Max of an array, in this case of weight - pounds
lakers_weight_array.min(), lakers_weight_array.max()

(180, 253)

In [184]:
# Min and Max of an array, in this case of height - inches
lakers_height_array.min(), lakers_height_array.max()

(73, 82)

In [185]:
# Calculating standard deviation
lakers_weight_array.std(), lakers_height_array.std()

(27.817979797246238, 3.286335345030997)

In [187]:
# Percentile
np.percentile(lakers_height_array,50),np.percentile(lakers_height_array,75),np.percentile(lakers_height_array,90)

(78.0, 81.0, 81.6)

In [188]:
# Percentile
np.percentile(lakers_weight_array,50),np.percentile(lakers_weight_array,75),np.percentile(lakers_weight_array,90)

(215.0, 250.0, 251.8)

Same task for the GSW:

In [190]:
# Summation  (result in inches, pounds)
print(np.sum(gsw_height_array))
print(np.sum(gsw_weight_array))

390
1054


In [191]:
# Average 
np.average(gsw_height_array),np.average(gsw_weight_array)

(78.0, 210.8)

In [192]:
# Min and Max of GSW height/ weight
gsw_weight_array.min(), gsw_weight_array.max(), gsw_height_array.min(), gsw_height_array.max()

(185, 230, 74, 81)

In [195]:
# Percentile weight
np.percentile(gsw_weight_array,50),np.percentile(gsw_weight_array,75),np.percentile(gsw_height_array,90)

(220.0, 222.0, 80.2)

In [194]:
# Percentile height
np.percentile(gsw_height_array,50),np.percentile(gsw_height_array,75),np.percentile(gsw_height_array,90)

(78.0, 79.0, 80.2)

Top 10 Highest Paid NBA Players Insights

In [197]:
# Capstone Data

top10_height = [value for data in bmi_data["Top 10 Highest Paid NBA Players"] for key, value in data.items() if key == "Height"]
top10_weight = [value for data in bmi_data["Top 10 Highest Paid NBA Players"] for key, value in data.items() if key == "Weight"]

print(top10_height)
print(top10_weight)

[81, 75, 82, 77, 74, 74, 80, 83, 78]
[250, 200, 240, 220, 185, 194, 220, 243, 220]


In [198]:
a = np.array([45,16,73])
b = np.array([4,3,1])
print(np.mod(a,b))

[1 1 0]


Numpy arrays are homogeneous whereas python lists are not

Variance measures how the various BMIs of the players vary from the mean


In [199]:
a = ([1,2,1],[1,1,1],[2,1,1])
np.prod(a,axis=1)

array([2, 1, 2])